# Generated by Django 6.1.1 on 2026-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('roadwork', 'Roboty drogowe'), ('event', 'Wydarzenie'), ('accident', 'Wypadek / awaria'), ('closure', 'Zamknięcie drogi')], default='roadwork', max_length=20, verbose_name='Rodzaj')),
                ('organization', models.CharField(blank=True, help_text='np. ZIKiT, Wodociągi, Energetyka', max_length=120, verbose_name='Zgłaszający')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('detour', models.CharField(blank=True, max_length=300, verbose_name='Objazd')),
                ('start_lng', models.FloatField(verbose_name='Początek - dł. geogr.')),
                ('end_lat', models.FloatField(verbose_name='Koniec - szer. geogr.')),
                ('end_lng', models.FloatField(verbose_name='Koniec - dł. geogr.')),
                ('start_at', models.DateTimeField(verbose_name='Od')),
                ('end_at', models.DateTimeField(verbose_name='Do')),
            ],
            options={
                'verbose_name': 'Ograniczenie drogowe',
                'verbose_name_plural': 'Ograniczenia drogowe',
                'ordering': ['start_at'],
            },
        ),
    ]
