# Generated by Django 6.1.1 on 2026-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadrestriction',
            name='start_lat',
            field=models.FloatField(default=19.956, verbose_name='Początek - szer. geogr.'),
            preserve_default=False,
        ),
    ]
