# Generated by Django 6.1.1 on 2026-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_max_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='empty_slots',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='max_slots',
            field=models.PositiveBigIntegerField(blank=True, default=100),
        ),
    ]
